@artifact.package@

/**
 * Note that this is a fixture example for the @artifact.name@ specification that 
 * has been kindly generated by the Grails Concordion plugin.
 *
 * You should change this example to adapt it conveniently to your application 
 * under test.
 */
class @artifact.name@ {

    def split(String fullName) {
	def result
	if (fullName) {
	    def words = fullName.split(/\s/)
	    result = new Result(words[0], words[1])
	}
	result
    }

    public class Result {
	def firstName
	def lastName
	
	public Result(firstName, lastName) {
	    this.firstName = firstName
	    this.lastName = lastName
	}
    }

}