<html xmlns:concordion="http://www.concordion.org/2007/concordion" xmlns:ext="urn:concordion-extensions:2010">
<head>
    <title>@artifact.capitalizedName@</title>
</head>
<body>

    <h1>@artifact.capitalizedName@</h1>

    <div style="background-color: #aaa; padding: 1em;">
        <p>
            Note that the following is a template example for the "@artifact.name@" specification that has been kindly 
            generated by the <a href="http://grails.org/plugin/concordion">Grails Concordion plugin</a>.
            You should change this example to adapt it conveniently to your application.
	</p>
	<p>The following example is taken from the <a href="http://concordion.org/">Concordion</a> tutorial.</p>
    </div>

    <hr/>

    <h2>Splitting Names</h2>

    <p>
        To help personalise our mailshots we want to have the first name
        and last name of the customer. Unfortunately the customer data
        that we are supplied only contains full names.
    </p>

    <p>
        The system therefore attempts to break a supplied full name into
        its constituents by splitting around whitespace.
    </p>

    <div class="example">

        <h3>Example</h3>

        <p>
            The full name
            <span concordion:execute="#result = split(#TEXT)">John Smith</span>
            will be broken into first name
            <span concordion:assertEquals="#result.firstName">John</span>
            and last name
            <span concordion:assertEquals="#result.lastName">Smith</span>.
        </p>

    </div>

    <h2>Further Details</h2>
    <ul>
        <li><a href="#">Other active specification</a></li>
        <li><a href="#">Another one</a></li>
    </ul>

</body>
</html>
